# Site settings
title: Mirza M. Elahi
email: me5vp@virginia.edu
description: > # this means to ignore newlines until "baseurl:"

baseurl: "/~me5vp" # the subpath of your site, e.g. /blog/
url: "http://people.virginia.edu" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  mirzaelahi
linkedin_username:  mirzamonzur
googlescholar_username: Mirza Elahi
googlescholar_id: DoijB9AAAAAJ&hl=en
researchgate_username: Mirza_Elahi3
copyright_start: 2014

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Graduate Student"
excerpt_separator: "<!--more-->"
port: 3000

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
